Areas/Admin/Controllers/AdminCategoryController.cs
namespace MvcForum.Web.Areas.Admin.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using Core.Constants;
    using Core.ExtensionMethods;
    using Core.Interfaces;
    using Core.Interfaces.Services;
    using Core.Models.Entities;
    using ExtensionMethods;
    using ViewModels;
    using ViewModels.Admin;

    [Authorize(Roles = Constants.AdminRoleName)]
    public class AdminCategoryController : BaseAdminController
    {
        private readonly ICategoryService _categoryService;

        public AdminCategoryController(ILoggingService loggingService,
            IMvcForumContext context,
            IMembershipService membershipService,
            ILocalizationService localizationService,
            ICategoryService categoryService,
            ISettingsService settingsService)
            : base(loggingService, membershipService, localizationService, settingsService, context)
        {
            _categoryService = categoryService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public PartialViewResult GetMainCategories()
        {
            var viewModel = new ListCategoriesViewModel
            {
                Categories = _categoryService.GetAll().OrderBy(x => x.SortOrder)
            };
            return PartialView(viewModel);
        }

        /// <summary>
        ///     Removes the category image
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult RemoveCategoryImage(Guid id)
        {
            var category = _categoryService.Get(id);
            category.Image = string.Empty;
            Context.SaveChanges();
            return RedirectToAction("EditCategory", new {id});
        }

        public ActionResult CreateCategory()
        {
            var categoryViewModel = new CategoryEditViewModel
            {
                AllCategories = _categoryService.GetBaseSelectListCategories(_categoryService.GetAll()),
                AllSections = _categoryService.GetAllSections().ToSelectList()
            };
            return View(categoryViewModel);
        }

        /// <summary>
        ///     Create category logic
        /// </summary>
        /// <param name="categoryViewModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateCategory(CategoryEditViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                var category = categoryViewModel.ToCategory();

                var categoryResult = await _categoryService.Create(category, categoryViewModel.Files,
                    categoryViewModel.ParentCategory, categoryViewModel.Section);
                if (!categoryResult.Successful)
                {
                    ModelState.AddModelError("", categoryResult.ProcessLog.FirstOrDefault());
                }
                else
                {
                    // We use temp data because we are doing a redirect
                    TempData[Constants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = "Category Created",
                        MessageType =
                            GenericMessages.success
                    };
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ModelState.AddModelError("", "There was an error creating the category");
            }

            categoryViewModel.AllCategories = _categoryService.GetBaseSelectListCategories(_categoryService.GetAll());
            categoryViewModel.AllSections = _categoryService.GetAllSections().ToSelectList();

            return View(categoryViewModel);
        }

        public ActionResult EditCategory(Guid id)
        {
            var category = _categoryService.Get(id);
            var categoryViewModel = category.ToEditViewModel(_categoryService.GetBaseSelectListCategories(_categoryService.GetAll().Where(x => x.Id != category.Id).ToList()), _categoryService.GetAllSections().ToSelectList());

            return View(categoryViewModel);
        }

        [HttpPost]
        public async Task<ActionResult> EditCategory(CategoryEditViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                // Reset the select list
                categoryViewModel.AllCategories = _categoryService.GetBaseSelectListCategories(_categoryService.GetAll()
                    .Where(x => x.Id != categoryViewModel.Id)
                    .ToList());

                var categoryToEdit = _categoryService.Get(categoryViewModel.Id);

                var category = categoryViewModel.ToCategory(categoryToEdit);

                var categoryResult = await _categoryService.Edit(category, categoryViewModel.Files,
                    categoryViewModel.ParentCategory, categoryViewModel.Section);
                if (!categoryResult.Successful)
                {
                    ModelState.AddModelError("", categoryResult.ProcessLog.FirstOrDefault());
                }
                else
                {
                    // We use temp data because we are doing a redirect
                    TempData[Constants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = "Category Edited",
                        MessageType = GenericMessages.success
                    };

                    // Set the view model
                    categoryViewModel = categoryResult.EntityToProcess.ToEditViewModel(
                        _categoryService.GetBaseSelectListCategories(_categoryService.GetAll()
                            .Where(x => x.Id != categoryViewModel.Id)
                            .ToList()), _categoryService.GetAllSections().ToSelectList());
                }
            }

            return View(categoryViewModel);
        }

        public ActionResult DeleteCategoryConfirmation(Guid id)
        {
            var cat = _categoryService.Get(id);
            var subCats = _categoryService.GetAllSubCategories(id).ToList();
            var viewModel = new DeleteCategoryViewModel
            {
                Id = cat.Id,
                Category = cat,
                SubCategories = subCats
            };

            return View(viewModel);
        }

        public async Task<ActionResult> DeleteCategory(Guid id)
        {
            var cat = _categoryService.Get(id);
            var categoryResult = await _categoryService.Delete(cat);

            if (!categoryResult.Successful)
            {
                TempData[Constants.MessageViewBagName] = new GenericMessageViewModel
                {
                    Message = categoryResult.ProcessLog.FirstOrDefault(),
                    MessageType = GenericMessages.danger
                };
            }
            else
            {
                TempData[Constants.MessageViewBagName] = new GenericMessageViewModel
                {
                    Message = "Category Deleted",
                    MessageType = GenericMessages.success
                };
            }

            return RedirectToAction("Index");
        }

        public ActionResult SyncCategoryPaths()
        {
            try
            {
                // var all categories
                var all = _categoryService.GetAll();

                // Get all the categories
                var maincategories = all.Where(x => x.ParentCategory == null).ToList();

                // Get the sub categories
                var subcategories = all.Where(x => x.ParentCategory != null).ToList();

                // loop through the main categories and get all it's sub categories
                foreach (var maincategory in maincategories)
                {
                    // get a list of sub categories, from this category
                    var subCats = new List<Category>();
                    subCats = GetAllCategorySubCategories(maincategory, subcategories, subCats);

                    // Now loop through these subcategories and set the paths
                    var count = 1;
                    var prevCatId = string.Empty;
                    var prevPath = string.Empty;
                    foreach (var cat in subCats)
                    {
                        if (count == 1)
                        {
                            // If first count just set the parent category Id
                            cat.Path = maincategory.Id.ToString();
                        }
                        else
                        {
                            // If past one, then we use the previous category
                            if (string.IsNullOrWhiteSpace(prevPath))
                            {
                                cat.Path = prevCatId;
                            }
                            else
                            {
                                cat.Path = string.Concat(prevPath, ",", prevCatId);
                            }
                        }
                        prevCatId = cat.Id.ToString();
                        prevPath = cat.Path;
                        count++;
                    }

                    // Save changes on each category
                    Context.SaveChanges();
                }


                TempData[Constants.MessageViewBagName] = new GenericMessageViewModel
                {
                    Message = "Category Paths Synced",
                    MessageType = GenericMessages.success
                };
                Context.SaveChanges();
            }
            catch (Exception)
            {
                Context.RollBack();

Areas/Admin/Controllers/PermissionsController.cs
namespace MvcForum.Web.Areas.Admin.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using Core.Constants;
    using Core.Interfaces;
    using Core.Interfaces.Services;
    using Core.Models.Entities;
    using Web.ViewModels;
    using Web.ViewModels.Admin;
    using Web.ViewModels.Category;

    [Authorize(Roles = Constants.AdminRoleName)]
    public class PermissionsController : BaseAdminController
    {
        private readonly ICategoryPermissionForRoleService _categoryPermissionForRoleService;
        private readonly ICategoryService _categoryService;
        private readonly IGlobalPermissionForRoleService _globalPermissionForRoleService;
        private readonly IPermissionService _permissionService;
        private readonly IRoleService _roleService;

        public PermissionsController(ILoggingService loggingService, IRoleService roleService,
            ILocalizationService localizationService, IPermissionService permissionService,
            ICategoryService categoryService, ICategoryPermissionForRoleService categoryPermissionForRoleService,
            IMembershipService membershipService, ISettingsService settingsService,
            IGlobalPermissionForRoleService globalPermissionForRoleService, IMvcForumContext context)
            : base(loggingService, membershipService, localizationService, settingsService, context)
        {
            _roleService = roleService;
            _permissionService = permissionService;
            _categoryService = categoryService;
            _categoryPermissionForRoleService = categoryPermissionForRoleService;
            _globalPermissionForRoleService = globalPermissionForRoleService;
        }

        /// <summary>
        ///     List of roles to apply permissions to
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var permViewModel = new ChoosePermissionsViewModel
            {
                MembershipRoles = _roleService.AllRoles().ToList(),
                Permissions = _permissionService.GetAll().ToList()
            };
            return View(permViewModel);
        }

        /// <summary>
        ///     Add / Remove permissions for a role on each category
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult EditPermissions(Guid id)
        {
            var role = _roleService.GetRole(id);
            var permViewModel = new EditPermissionsViewModel
            {
                MembershipRole = role,
                Permissions = _permissionService.GetAll().ToList(),
                Categories = _categoryService.GetAll(),
                CurrentGlobalPermissions = _roleService.GetPermissions(null, role)
            };

            return View(permViewModel);
        }

        public ActionResult EditCategoryPermissions(Guid id)
        {
            var category = _categoryService.Get(id);
            var catPermissionViewModel = new EditCategoryPermissionsViewModel
            {
                Category = category,
                Permissions = _permissionService.GetAll().ToList(),
                Roles = _roleService.AllRoles()
                    .Where(x => x.RoleName != Constants.AdminRoleName)
                    .OrderBy(x => x.RoleName)
                    .ToList()
            };
            return View(catPermissionViewModel);
        }

        public ActionResult PermissionTypes()
        {
            var permViewModel = new ChoosePermissionsViewModel
            {
                Permissions = _permissionService.GetAll().ToList()
            };
            return View(permViewModel);
        }

        /// <summary>
        ///     Add a new permission type into the permission table
        /// </summary>
        /// <returns></returns>
        public ActionResult AddType()
        {
            return View(new AddTypeViewModel());
        }

        [HttpPost]
        public ActionResult AddType(AddTypeViewModel permissionViewModel)
        {
            try
            {
                var permission = new Permission
                {
                    Name = permissionViewModel.Name,
                    IsGlobal = permissionViewModel.IsGlobal
                };

                _permissionService.Add(permission);
                TempData[Constants.MessageViewBagName] = new GenericMessageViewModel
                {
                    Message = "Permission Added",
                    MessageType = GenericMessages.success
                };
                Context.SaveChanges();
            }
            catch (Exception ex)
            {
                Context.RollBack();
                LoggingService.Error(ex);
                throw;
            }


            return RedirectToAction("Index");
        }

        [HttpPost]
        public void UpdatePermission(AjaxEditPermissionViewModel ajaxEditPermissionViewModel)
        {
            try
            {
                if (Request.IsAjaxRequest())
                {
                    if (ajaxEditPermissionViewModel.Category == Guid.Empty)
                    {
                        // If category is empty guid then this is a global permission

                        var gpr = new GlobalPermissionForRole
                        {
                            MembershipRole =
                                _roleService.GetRole(ajaxEditPermissionViewModel.MembershipRole),
                            Permission =
                                _permissionService.Get(ajaxEditPermissionViewModel.Permission),
                            IsTicked = ajaxEditPermissionViewModel.HasPermission
                        };
                        _globalPermissionForRoleService.UpdateOrCreateNew(gpr);
                    }
                    else
                    {
                        // We have a category so it's a category permission 

                        var mappedItem = new CategoryPermissionForRole
                        {
                            Category = _categoryService.Get(ajaxEditPermissionViewModel.Category),
                            MembershipRole =
                                _roleService.GetRole(ajaxEditPermissionViewModel.MembershipRole),
                            Permission =
                                _permissionService.Get(ajaxEditPermissionViewModel.Permission),
                            IsTicked = ajaxEditPermissionViewModel.HasPermission
                        };
                        _categoryPermissionForRoleService.UpdateOrCreateNew(mappedItem);
                    }
                }
                Context.SaveChanges();
            }
            catch (Exception ex)
            {
                Context.RollBack();
                LoggingService.Error(ex);
                throw;
            }
        }

        public ActionResult DeletePermission(Guid id)
        {
            try
            {
                var permission = _permissionService.Get(id);
                _permissionService.Delete(permission);

                TempData[Constants.MessageViewBagName] = new GenericMessageViewModel
                {
                    Message = "Permission Deleted",
                    MessageType = GenericMessages.success
                };
                Context.SaveChanges();
            }
            catch (Exception ex)
            {
                Context.RollBack();
                LoggingService.Error(ex);
                throw;
            }

            return RedirectToAction("Index");
        }
    }
}

Areas/Admin/Views/Permissions/AddType.cshtml
@using MvcForum.Web.Application.ExtensionMethods
@model MvcForum.Web.ViewModels.Admin.AddTypeViewModel

@{
    ViewBag.Title = "Add Permission Type";
}

<div class="backbutton"><a href="@Url.Action("PermissionTypes")" class="btn-mvc-green">&lt;&lt; Go Back</a></div>

<div class="panel">
    <div class="panel-heading">
        <h5>@ViewBag.Title</h5>
    </div>
    <div class="panel-content">
        @using (Html.BeginForm("AddType", "Permissions", FormMethod.Post))
        {
            @Html.ValidationSummary(false)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name)
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Name)
                </div>

                <div class="checkbox">
                    @using (Html.BeginLabelFor(m => m.IsGlobal, new { @class = "checkbox" }))
                    {
                        @Html.CheckBoxFor(m => m.IsGlobal)
                    }
                    @Html.ValidationMessageFor(m => m.IsGlobal)
                </div>

                <div class="submit-holder">
                    <input type="submit" class="btn-mvc-green btn-mvc-large" value="Create" />
                </div>

        }
    </div>
</div>

Areas/Admin/Views/Permissions/EditCategoryPermissions.cshtml
@using MvcForum.Core
@model MvcForum.Web.ViewModels.Category.EditCategoryPermissionsViewModel
@{
    ViewBag.Title = "Edit Permissions";
    var allPermission = Model.Category.CategoryPermissionForRoles;
}
@section AdminPageHeader
{
    Edit Role Permissions for Category @Model.Category.Name <img src="@Url.Content("~/Content/admin/Images/ajax-loader.gif")" alt="Please Wait" style="display: none;" class="editpermissionsspinner" /> <span class="label label-success ajaxsuccessshow" style="display: none;">Success</span>
}
<div class="backbutton">
    <a href="@Url.Action("EditCategory", "AdminCategory", new {Id = Model.Category.Id})" class="btn-mvc-green">&lt;&lt; Go Back</a>
</div>
<div class="panel">
    <div class="panel-heading">
        <h5>Role Permissions</h5>
    </div>
    <div class="panel-content">

        <p>Role permissions are all actions a role is allowed to do (Or not do) within a specific category.</p>
        <div class="tablescroll">
            <table class="table table-bordered table-striped permissiontable">
                <thead>
                    <tr>
                        <th>Category</th>
                        @foreach (var permissionType in Model.Permissions.Where(x => !x.IsGlobal))
                        {
                            <th>@permissionType.Name</th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var role in Model.Roles)
                    {
                        <tr>
                            <td style="width:160px;">
                                @role.RoleName
                            </td>
                            @foreach (var permission in Model.Permissions.Where(x => !x.IsGlobal))
                            {
                                var isChecked = "";
                                var isDisabled = DisableCheckBox(permission.Name, role.RoleName);
                                var catPermission = allPermission.FirstOrDefault(x => x.Permission.Id == permission.Id && x.MembershipRole.Id == role.Id && x.Category.Id == Model.Category.Id);
                                <td>
                                    @if (catPermission != null)
                                    {
                                        // bingo we have this permission
                                        isChecked = catPermission.IsTicked ? " checked" : "";
                                    }
                                    <span class="permissioncheckbox">
                                        <input data-permisssion="@permission.Id" data-category="@Model.Category.Id" data-role="@role.Id" type="checkbox" id="@permission.Id-@Model.Category.Id" @isChecked @isDisabled />
                                    </span>
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="panel">
    <div class="panel-heading">
        <h5>Descriptions</h5>
    </div>
    <div class="panel-content">
        <h6>@ForumConfiguration.Instance.PermissionAttachFiles</h6>
        <p>If you tick this permission, users in this role will be able to attach files to topics and posts for download (file types and size can be restricted in web.config app settings - FileUploadAllowedExtensions and FileUploadMaximumFileSizeInBytes)</p>
        <h6>@ForumConfiguration.Instance.PermissionCreatePolls</h6>
        <p>If you tick this, then users in this role will be able to create polls in a topic.</p>
        <h6>@ForumConfiguration.Instance.PermissionVoteInPolls</h6>
        <p>If you tick this, users in this role will be able to vote in polls (As long as Create Polls is enabled)</p>
        <h6>@ForumConfiguration.Instance.PermissionCreateTopics</h6>
        <p>If you tick this, users in this role will be able to create topics</p>
        <h6>@ForumConfiguration.Instance.PermissionDeletePosts</h6>
        <p>If you tick this, users in this role will be able to delete other users posts and topics (Good Moderator permission)</p>
        <h6>@ForumConfiguration.Instance.PermissionEditPosts</h6>
        <p>If you tick this, users in this role will be able to edit other users posts and topics (Good Moderator permission)</p>
        <h6>@ForumConfiguration.Instance.PermissionLockTopics</h6>
        <p>If you tick this, users in this role will be able to lock topics, stopping any further posting in it.</p>
        <h6>@ForumConfiguration.Instance.PermissionCreateStickyTopics</h6>
        <p>If you tick this, users in this role will be able to make a sticky topic (Pin the topic) which will always be shown at the top of a category.</p>
        <h6>@ForumConfiguration.Instance.PermissionReadOnly</h6>
        <p>If you tick this, users in this role will not be able to post in the Category.</p>
        <h6>@ForumConfiguration.Instance.PermissionDenyAccess</h6>
        <p>If you tick this, users will not be able to access or see the Category - Also they won't be able to see any posts, topics or tags that were created in it either (Private Categories).</p>
    </div>
</div>
@helper DisableCheckBox(string permissionName, string roleName)
    {
        if (roleName == Constants.GuestRoleName && permissionName != ForumConfiguration.Instance.PermissionDenyAccess)
        {
            <text>disabled</text>
        }
        else
        {
            <text></text>
        }
}

Areas/Admin/Views/Permissions/Index.cshtml
@using MvcForum.Core.Constants
@model MvcForum.Web.ViewModels.Admin.ChoosePermissionsViewModel
@{
    ViewBag.Title = "Update Permissions";
}

<div class="panel">
    <div class="panel-heading">
        <h5>@ViewBag.Title</h5>
    </div>
    <div class="panel-content">
        <p>This section allows you to update and edit permissions, firstly select the role you want to edit the permissions for</p>
        <div class="row">
            <div class="col-md-4">
                @foreach (var role in Model.MembershipRoles)
                {
                    <ul class="rolepermissionlist">
                        @if (role.RoleName != Constants.AdminRoleName)
                        {
                            <li><a href="@Url.Action("EditPermissions", new { role.Id })" class="btn-mvc-green btn-mvc-large btn-mvc-fullwidth">@role.RoleName</a></li>
                        }
                    </ul>
                }
            </div>
        </div>

    </div>
</div>

Areas/Admin/Views/Permissions/PermissionTypes.cshtml
@model MvcForum.Web.ViewModels.Admin.ChoosePermissionsViewModel
@{
    ViewBag.Title = "Permission Types";
}
<div class="permissiontypes">

    <div class="row">

        <div class="col-md-6">
            <div class="panel">
                <div class="panel-heading">
                    <h5>Add Permissions</h5>
                </div>
                <div class="panel-content">
                    <p>It's super simple to add your own custom permissions to the forum, you firstly need to add it into the database using the button below.</p>
                    <p>
                        Then you after you have done that, you can check the permission based on the role (And Category). You just pull out the permission
                        from a PermissionSet using the name of the permission you just added to the database. We put all permission names into constants to make it easier. Example below.
                    </p>
                    <pre>
var permissions = RoleService.GetPermissions(category, UsersRole);
permissions["YourCustomPermissionName"].IsTicked</pre>
                    <p>Global permissions are returned with the call above, but if you just want to get global permissions you call the same method, but pass in null for the category.</p>
                    <pre>
var permissions = RoleService.GetPermissions(null, UsersRole);</pre>
                    <p>&nbsp;</p>
                    <p><a href="@Url.Action("AddType")" class="btn-mvc-green btn-mvc-large">Add New Permission Type</a></p>
                </div>
            </div>
        </div>

        <div class="col-md-6">

            <p><strong style="color: maroon; text-decoration: underline;">WARNING:</strong> Deleting permission types that are in use will break your forum, be VERY careful.</p>

            <div class="panel">
                <div class="panel-heading">
                    <h5>Current Permission Types</h5>
                </div>
                <ul class="list-group">
                    @foreach (var permission in Model.Permissions)
                    {
                        <li class="list-group-item">
                            <span class="badge">
                                <a href="@Url.Action("DeletePermission", "Permissions", new { id = permission.Id })" onclick="return confirm('Are you sure?')"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                            </span>
                            @permission.Name
                        </li>
                    }
                </ul>
            </div>

        </div>

    </div>

</div>