Areas/Admin/Controllers/AdminController.cs
namespace MvcForum.Web.Areas.Admin.Controllers
{
    using System.Web.Mvc;
    using Core.Constants;
    using Core.Interfaces;
    using Core.Interfaces.Services;
    using Core.Utilities;

    [Authorize(Roles = Constants.AdminRoleName)]
    public class AdminController : BaseAdminController
    {
        public AdminController(ILoggingService loggingService,
            IMembershipService membershipService,
            ILocalizationService localizationService,
            ISettingsService settingsService, IMvcForumContext context)
            : base(loggingService, membershipService, localizationService, settingsService, context)
        {
        }

        /// <summary>
        ///     Default page for the admin area
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        #region Utils

        [HttpPost]
        public void Aptitude()
        {
            try
            {
                var url = StringUtils.ReturnCurrentDomain();
                var postString = string.Concat("url=", url);
                var response = StringUtils.PostForm("http://www.mvcforum.com/base/MVCBase/DomainCheck", postString);
            }
            catch
            {
                // No need to do anything
            }
        }

        #endregion
    }
}

Areas/Admin/Controllers/AdminTagController.cs
namespace MvcForum.Web.Areas.Admin.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using Core;
    using Core.Constants;
    using Core.Interfaces;
    using Core.Interfaces.Services;
    using Core.Models.Entities;
    using Web.ViewModels;
    using Web.ViewModels.Admin;

    [Authorize(Roles = Constants.AdminRoleName)]
    public class AdminTagController : BaseAdminController
    {
        private readonly ITopicTagService _topicTagService;

        public AdminTagController(ILoggingService loggingService, IMembershipService membershipService,
            ILocalizationService localizationService, ISettingsService settingsService,
            ITopicTagService topicTagService, IMvcForumContext context)
            : base(loggingService, membershipService, localizationService, settingsService, context)
        {
            _topicTagService = topicTagService;
        }

        public async Task<ActionResult> Index(int? p, string search)
        {
            var pageIndex = p ?? 1;


            var allTags = string.IsNullOrWhiteSpace(search)
                ? await _topicTagService.GetPagedGroupedTags(pageIndex, ForumConfiguration.Instance.AdminListPageSize)
                : await _topicTagService.SearchPagedGroupedTags(search, pageIndex,
                    ForumConfiguration.Instance.AdminListPageSize);

            var memberListModel = new ListTagsViewModel
            {
                Tags = allTags,
                PageIndex = pageIndex,
                TotalCount = allTags.TotalCount,
                Search = search
            };

            return View(memberListModel);
        }

        private List<SelectListItem> TagsSelectList()
        {
            var list = new List<SelectListItem>();
            foreach (var tag in _topicTagService.GetAll().OrderBy(x => x.Tag).ToList())
            {
                list.Add(new SelectListItem
                {
                    Text = tag.Tag,
                    Value = tag.Id.ToString()
                });
            }
            return list;
        }

        public ActionResult MoveTags()
        {
            var viewModel = new MoveTagsViewModel
            {
                Tags = TagsSelectList()
            };
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult MoveTags(MoveTagsViewModel viewModel)
        {
            var oldTag = _topicTagService.Get(viewModel.CurrentTagId);
            var newTag = _topicTagService.Get(viewModel.NewTagId);

            // Look through the topics and add the new tag to it and remove the old!                
            var topics = new List<Topic>();
            topics.AddRange(oldTag.Topics);
            foreach (var topic in topics)
            {
                topic.Tags.Remove(oldTag);
                topic.Tags.Add(newTag);
            }

            // Reset the tags
            viewModel.Tags = TagsSelectList();

            try
            {
                Context.SaveChanges();
                ShowMessage(new GenericMessageViewModel
                {
                    Message = $"All topics tagged with {oldTag.Tag} have been updated to {newTag.Tag}",
                    MessageType = GenericMessages.success
                });
            }
            catch (Exception ex)
            {
                Context.RollBack();
                LoggingService.Error(ex);
                ShowMessage(new GenericMessageViewModel
                {
                    Message = $"Error: {ex.Message}",
                    MessageType = GenericMessages.danger
                });
            }

            return View(viewModel);
        }


        public ActionResult Manage(int? p, string search)
        {
            return RedirectToAction("Index", new {p, search});
        }


        public ActionResult Delete(string tag, int? p)
        {
            var page = p ?? 1;

            _topicTagService.DeleteByName(tag);

            TempData[Constants.MessageViewBagName] = new GenericMessageViewModel
            {
                Message = "Tags delete successfully",
                MessageType = GenericMessages.success
            };

            try
            {
                Context.SaveChanges();
            }
            catch (Exception ex)
            {
                Context.RollBack();
                LoggingService.Error(ex);
                ShowMessage(new GenericMessageViewModel
                {
                    Message = $"Delete failed: {ex.Message}",
                    MessageType = GenericMessages.danger
                });
            }
                        
            return RedirectToAction("Index",  new { p = page });
        }

        [HttpPost]
        public void UpdateTag(AjaxEditTagViewModel viewModel)
        {
            if (Request.IsAjaxRequest())
            {
                _topicTagService.UpdateTagNames(viewModel.NewName, viewModel.OldName);

                try
                {
                    Context.SaveChanges();
                }
                catch (Exception ex)
                {
                    Context.RollBack();
                    LoggingService.Error(ex);
                }
            }
        }
    }
}

Areas/Admin/Controllers/BatchController.cs
namespace MvcForum.Web.Areas.Admin.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using Core.Constants;
    using Core.Interfaces;
    using Core.Interfaces.Services;
    using Core.Models.Entities;
    using Web.ViewModels;
    using Web.ViewModels.Admin;

    [Authorize(Roles = Constants.AdminRoleName)]
    public class BatchController : BaseAdminController
    {
        private readonly ICategoryService _categoryService;
        private readonly IPrivateMessageService _privateMessageService;
        private readonly ITopicService _topicService;

        public BatchController(ILoggingService loggingService, IMembershipService membershipService,
            ILocalizationService localizationService, ISettingsService settingsService,
            ICategoryService categoryService, ITopicService topicService, IPrivateMessageService privateMessageService,
            IMvcForumContext context)
            : base(loggingService, membershipService, localizationService, settingsService, context)
        {
            _categoryService = categoryService;
            _topicService = topicService;
            _privateMessageService = privateMessageService;
        }

        #region Members

        public ActionResult BatchDeleteMembers()
        {
            return View(new BatchDeleteMembersViewModel { AmoutOfDaysSinceRegistered = 0, AmoutOfPosts = 0 });
        }

        /// <summary>
        /// Batch delete members
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BatchDeleteMembers(BatchDeleteMembersViewModel viewModel)
        {

            var membersToDelete = MembershipService.GetUsersByDaysPostsPoints(
                viewModel.AmoutOfDaysSinceRegistered,
                viewModel.AmoutOfPosts);

            var count = membersToDelete.Count;
            foreach (var membershipUser in membersToDelete)
            {
                var pipelineResult = await MembershipService.Delete(membershipUser);
                if (!pipelineResult.Successful)
                {
                    TempData[Constants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = pipelineResult.ProcessLog.FirstOrDefault(),
                        MessageType = GenericMessages.danger
                    };
                    return View();
                }
            }

            TempData[Constants.MessageViewBagName] = new GenericMessageViewModel
            {
                Message = $"{count} members deleted",
                MessageType = GenericMessages.success
            };

            return View();
        }

        #endregion

        #region Topics

        public ActionResult BatchMoveTopics()
        {
            var viewModel = new BatchMoveTopicsViewModel
            {
                Categories = _categoryService.GetAll()
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BatchMoveTopics(BatchMoveTopicsViewModel viewModel)
        {
            try
            {
                var categoryFrom = _categoryService.Get((Guid)viewModel.FromCategory);
                var categoryTo = _categoryService.Get((Guid)viewModel.ToCategory);

                var topicsToMove = _topicService.GetRssTopicsByCategory(int.MaxValue, categoryFrom.Id);
                var count = topicsToMove.Count;

                foreach (var topic in topicsToMove)
                {
                    topic.Category = categoryTo;
                }

                Context.SaveChanges();

                categoryFrom.Topics.Clear();

                viewModel.Categories = _categoryService.GetAll();

                Context.SaveChanges();

                TempData[Constants.MessageViewBagName] = new GenericMessageViewModel
                {
                    Message = $"{count} topics moved",
                    MessageType = GenericMessages.success
                };
            }
            catch (Exception ex)
            {
                Context.RollBack();
                LoggingService.Error(ex);
                TempData[Constants.MessageViewBagName] = new GenericMessageViewModel
                {
                    Message = ex.Message,
                    MessageType = GenericMessages.danger
                };
            }


            return View(viewModel);
        }

        #endregion

        #region Private Messages

        public ActionResult BatchDeletePrivateMessages()
        {
            var viewModel = new BatchDeletePrivateMessagesViewModel();
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BatchDeletePrivateMessages(BatchDeletePrivateMessagesViewModel viewModel)
        {
            try
            {
                var pms = _privateMessageService.GetPrivateMessagesOlderThan(viewModel.Days);
                var pmToDelete = new List<PrivateMessage>();
                pmToDelete.AddRange(pms);
                var count = pmToDelete.Count;
                foreach (var pm in pmToDelete)
                {
                    _privateMessageService.DeleteMessage(pm);
                }
                Context.SaveChanges();

                TempData[Constants.MessageViewBagName] = new GenericMessageViewModel
                {
                    Message = $"{count} Private Messages deleted",
                    MessageType = GenericMessages.success
                };
            }
            catch (Exception ex)
            {
                Context.RollBack();
                LoggingService.Error(ex);
                TempData[Constants.MessageViewBagName] = new GenericMessageViewModel
                {
                    Message = ex.Message,
                    MessageType = GenericMessages.danger
                };
            }


            return View(viewModel);
        }

        #endregion
    }
}

Areas/Admin/Controllers/LogController.cs
namespace MvcForum.Web.Areas.Admin.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using Core.Constants;
    using Core.Interfaces;
    using Core.Interfaces.Services;
    using Core.Models.General;
    using Web.ViewModels;
    using Web.ViewModels.Admin;

    [Authorize(Roles = Constants.AdminRoleName)]
    public class LogController : BaseAdminController
    {
        public LogController(ILoggingService loggingService, IMembershipService membershipService,
            ILocalizationService localizationService, ISettingsService settingsService, IMvcForumContext context) :
            base(loggingService, membershipService, localizationService, settingsService, context)
        {
        }

        public ActionResult Index()
        {
            IList<LogEntry> logs = new List<LogEntry>();

            try
            {
                logs = LoggingService.ListLogFile();
            }
            catch (Exception ex)
            {
                var err = $"Unable to access logs: {ex.Message}";
                TempData[Constants.MessageViewBagName] = new GenericMessageViewModel
                {
                    Message = err,
                    MessageType = GenericMessages.danger
                };

                LoggingService.Error(err);
            }

            return View(new ListLogViewModel {LogFiles = logs});
        }

        public ActionResult ClearLog()
        {
            LoggingService.ClearLogFiles();

            TempData[Constants.MessageViewBagName] = new GenericMessageViewModel
            {
                Message = "Log File Cleared",
                MessageType = GenericMessages.success
            };
            return RedirectToAction("Index");
        }
    }
}

Areas/Admin/Views/Dashboard/HighestViewedTopics.cshtml
@model MvcForum.Web.ViewModels.Admin.HighestViewedTopics

<div class="panel">
    <div class="panel-heading">
        <h5>Highest Viewed Topics</h5>
    </div>
    @if (Model.Topics.Any())
    {
        <ul class="list-group">
            @foreach (var topic in Model.Topics)
            {
                <li class="list-group-item">
                    <span class="badge">@topic.Views</span>
                    <a href="@topic.NiceUrl">@Html.Raw(topic.Name)</a>
                </li>
            }
        </ul>
    }
    else
    {
        <div class="panel-content">No data</div>
    }

</div>

Areas/Admin/Views/Dashboard/LatestUsers.cshtml
@model MvcForum.Web.ViewModels.Admin.LatestUsersViewModels

<div class="panel">
    <div class="panel-heading">
        <h5>Latest Users</h5>
    </div>
    @if (Model.Users.Any())
    {
        <ul class="list-group">
            @foreach (var user in Model.Users)
            {
                <li class="list-group-item">
                    <a href="@user.NiceUrl">@Html.Raw(user.UserName)</a> On @user.CreateDate.ToShortDateString()
                </li>
            }
        </ul>
    }
    else
    {
        <div class="panel-content">
            Nothing to show
        </div>
    }

</div>

Areas/Admin/Views/Dashboard/LowestPointPosts.cshtml
@model MvcForum.Web.ViewModels.Admin.LowestPointPostsViewModels


<div class="panel">
    <div class="panel-heading">
        <h5>Lowest Point Posts</h5>
    </div>
    @if (Model.Posts.Any())
    {
        <ul class="list-group">
            @foreach (var post in Model.Posts)
            {
                <li class="list-group-item">
                    <span class="badge">@post.VoteCount</span>
                    <a href="@post.Topic.NiceUrl">@post.Topic.Name</a> By <a href="@post.User.NiceUrl">@post.User.UserName</a>
                </li>
            }
        </ul>
    }
    else
    {
        <div class="panel-content">
            Nothing to show
        </div>
    }

</div>

Areas/Admin/Views/Dashboard/LowestPointUsers.cshtml
@model MvcForum.Web.ViewModels.Admin.LowestPointUsersViewModels

<div class="panel">
    <div class="panel-heading">
        <h5>Lowest Point Users</h5>
    </div>
    @if (Model.Users.Any())
    {
        <ul class="list-group">
            @foreach (var user in Model.Users)
            {
                <li class="list-group-item">
                    <span class="badge">@user.Value</span>
                    <a href="@user.Key.NiceUrl">@Html.Raw(user.Key.UserName)</a>
                </li>
            }
        </ul>
    }
    else
    {
        <div class="panel-body">
            Nothing to show
        </div>
    }

</div>

Areas/Admin/Views/Dashboard/MainAdminNav.cshtml
@using MvcForum.Core.Constants
@model MvcForum.Web.ViewModels.Admin.MainDashboardNavViewModel
@{
    var currentController = TempData[Constants.CurrentController].ToString();
    var currentAction = TempData[Constants.CurrentAction].ToString();
}
<ul class="nav navbar-right top-nav">
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> @User.Identity.Name <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>
                <a href="@Url.Action("Index", "PrivateMessage", new { area = "" })">
                    <i class="fa fa-fw fa-envelope"></i> Private Messages
                    @if (Model.PrivateMessageCount > 0)
                    {
                        <span class="badge">@Model.PrivateMessageCount</span>
                    }
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="@Url.Action("LogOff", "Members", new { area = "" })"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
            </li>
        </ul>
    </li>
</ul>
<div class="collapse navbar-collapse mvcforum-nav">
    <ul class="nav navbar-nav side-nav">
        <li>
            <a href="@Url.Content("~/")"><i class="fa fa-fw fa-arrow-left"></i> Main Site</a>
        </li>
        <li>
            <a href="@Url.Action("Index", "Admin", new { area = "Admin" })" class="@(currentController == "admin" && currentAction == "index" ? "active" : "")">
                <i class="fa fa-fw fa-dashboard"></i> Dashboard
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "Settings", new { area = "Admin" }, null)" class="@(currentController == "settings" && currentAction == "index" ? "active" : "")">
                <i class="fa fa-fw fa-cogs"></i> Main Settings
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "AdminCategory", new { area = "Admin" }, null)" class="@(currentController == "admincategory" && currentAction == "index" ? "active" : "")">
                <i class="fa fa-fw fa-folder-open-o"></i> Categories
            </a>
        </li>
        <li>
            <a href="@Url.Action("Sections", "AdminCategory", new { area = "Admin" }, null)" class="@(currentController == "admincategory" && currentAction == "sections" ? "active" : "")">
                <i class="fa fa-fw fa-folder-open-o"></i> Sections
            </a>
        </li>
        <li>
            <a href="#" data-toggle="collapse" data-target="#tags">
                <i class="fa fa-fw fa-tags"></i> Tags <i class="fa fa-fw fa-caret-down"></i>
            </a>
            <ul id="tags" class="collapse">
                <li>
                    <a href="@Url.Action("Index", "AdminTag", new { area = "Admin" })" class="@(currentController == "admintag" && currentAction == "index" ? "active" : "")">
                        Manage Tags
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("MoveTags", "AdminTag", new { area = "Admin" }, null)" class="@(currentController == "admintag" && currentAction == "movetags" ? "active" : "")">
                        Change Tags On Topics
                    </a>
                </li>
            </ul>

        </li>
        <li>
            <a href="@Url.Action("Index", "AdminBadge", new { area = "Admin" })" class="@(currentController == "adminbadge" && currentAction == "index" ? "active" : "")">
                <i class="fa fa-fw fa-trophy"></i> Badges
            </a>
        </li>
        <li>
            <a href="#" data-toggle="collapse" data-target="#permissions">
                <i class="fa fa-fw fa-check-square-o"></i> Permissions <i class="fa fa-fw fa-caret-down"></i>
            </a>
            <ul id="permissions" class="collapse">
                <li>
                    <a href="@Url.Action("Index", "Permissions", new { area = "Admin" }, null)" class="@(currentController == "permissions" && currentAction == "index" ? "active" : "")">Manage Permissions</a>
                </li>
                <li>
                    <a href="@Url.Action("PermissionTypes", "Permissions", new { area = "Admin" }, null)" class="@(currentController == "permissions" && currentAction == "permissiontypes" ? "active" : "")">Add/Remove Permission Types</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#" data-toggle="collapse" data-target="#membership">
                <i class="fa fa-fw fa-users"></i> Membership <i class="fa fa-fw fa-caret-down"></i>
            </a>
            <ul id="membership" class="collapse">
                <li>
                    <a href="@Url.Action("Manage", "Account", new { area = "Admin" }, null)" class="@(currentController == "account" && currentAction == "manage" ? "active" : "")">Manage Users</a>
                </li>
                <li>
                    <a href="@Url.Action("ListAllRoles", "Account", new { area = "Admin" }, null)" class="@(currentController == "account" && currentAction == "listallroles" ? "active" : "")">Manage Roles</a>
                </li>
                <li>
                    <a href="@Url.Action("AddRole", "Account", new { area = "Admin" }, null)" class="@(currentController == "account" && currentAction == "addrole" ? "active" : "")">Add Roles</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "AdminSocial", new { area = "Admin" }, null)" class="@(currentController == "adminsocial" && currentAction == "index" ? "active" : "")">Social Logins</a>
                </li>
                <li>
                    <a href="@Url.Action("Members", "ImportExport", new { area = "Admin" }, null)" class="@(currentController == "importexport" && currentAction == "members" ? "active" : "")">Import / Export</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#" data-toggle="collapse" data-target="#spam">
                <i class="fa fa-fw fa-frown-o"></i> Spam Prevention <i class="fa fa-fw fa-caret-down"></i>
            </a>
            <ul id="spam" class="collapse">
                <li>
                    <a href="@Url.Action("Index", "BannedEmail", new { area = "Admin" })" class="@(currentController == "bannedemail" && currentAction == "index" ? "active" : "")">Ban Emails</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "BannedWord", new { area = "Admin" })" class="@(currentController == "bannedword" && currentAction == "index" ? "active" : "")">Banned &amp; Stop Words</a>
                </li>
                <li>
                    <a href="@Url.Action("Akismet", "AdminSpam", new { area = "Admin" })" class="@(currentController == "adminspam" && currentAction == "akismet" ? "active" : "")">Akismet</a>
                </li>
                <li>
                    <a href="@Url.Action("RegistrationQuestion", "AdminSpam", new { area = "Admin" })" class="@(currentController == "adminspam" && currentAction == "registrationquestion" ? "active" : "")">Registration Question</a>
                </li>
                <li>
                    <a href="@Url.Action("SpamReporting", "AdminSpam", new { area = "Admin" })" class="@(currentController == "adminspam" && currentAction == "spamreporting" ? "active" : "")">Spam Reporting</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#" data-toggle="collapse" data-target="#language">
                <i class="fa fa-fw fa-language"></i> Languages <i class="fa fa-fw fa-caret-down"></i>
            </a>
            <ul id="language" class="collapse">
                <li>
                    <a href="@Url.Action("Create", "AdminLanguage", new { area = "Admin" })" class="@(currentController == "adminlanguage" && currentAction == "create" ? "active" : "")">Add Language</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "AdminLanguage", new { area = "Admin" })" class="@(currentController == "adminlanguage" && currentAction == "index" ? "active" : "")">Edit Language</a>
                </li>
                <li>
                    <a href="@Url.Action("Languages", "ImportExport", new { area = "Admin" })" class="@(currentController == "importexport" && currentAction == "languages" ? "active" : "")">Import / Export</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="@Url.Action("CustomCode", "Settings", new { area = "Admin" }, null)" class="@(currentController == "settings" && currentAction == "customcode" ? "active" : "")"><i class="fa fa-fw fa-code"></i> Custom Code</a>
        </li>
        <li>
            <a href="#" data-toggle="collapse" data-target="#batch">
                <i class="fa fa-fw fa-bolt"></i> Batch Tools <i class="fa fa-fw fa-caret-down"></i>
            </a>
            <ul id="batch" class="collapse">
                <li>
                    <a href="@Url.Action("BatchDeleteMembers", "Batch", new { area = "Admin" }, null)" class="@(currentController == "batch" && currentAction == "batchdeletemembers" ? "active" : "")">Batch Delete Members</a>
                </li>
                <li>
                    <a href="@Url.Action("BatchMoveTopics", "Batch", new { area = "Admin" }, null)" class="@(currentController == "batch" && currentAction == "batchmovetopics" ? "active" : "")">Batch Move Topics</a>
                </li>
                <li>
                    <a href="@Url.Action("BatchDeletePrivateMessages", "Batch", new { area = "Admin" }, null)" class="@(currentController == "batch" && currentAction == "batchdeleteprivatemessages" ? "active" : "")">Batch Delete Private Messages</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="@Url.Action("Index", "Log", new { area = "Admin" })" class="@(currentController == "log" && currentAction == "index" ? "active" : "")"><i class="fa fa-fw fa-file-text-o"></i> Log</a>
        </li>
    </ul>
</div>

Areas/Admin/Views/Dashboard/MvcForumLatestNews.cshtml
@model MvcForum.Web.ViewModels.Admin.LatestNewsViewModel


<div class="panel">
    <div class="panel-heading">
        <h5>MvcForum Latest News</h5>
    </div>
    @if (Model.RssFeed.Any())
    {
        <ul class="list-group">
            @foreach (var rssItem in Model.RssFeed)
            {
                <li class="list-group-item">
                    <a href="@rssItem.Link" target="_blank">@rssItem.Title</a>
                </li>
            }
        </ul>
    }
    else
    {
        <div class="panel-body">
            Nothing to show
        </div>
    }

</div>

Areas/Admin/Views/Dashboard/TodaysTopics.cshtml
@model MvcForum.Web.ViewModels.Admin.TodaysTopics


<div class="panel">
    <div class="panel-heading">
        <h5>Todays Topics</h5>
    </div>

        @if (Model.Topics.Any())
        {
            <ul class="list-group">
                @foreach (var topic in Model.Topics)
                {
                    <li class="list-group-item">
                        <a href="@topic.NiceUrl">@Html.Raw(topic.Name)</a> By <a href="@topic.User.NiceUrl">@topic.User.UserName</a>
                    </li>
                }
            </ul>
        }
        else
        {
            <div class="panel-body">
                Nothing to show
            </div>
        }
 
</div>